services:
  zapimediaapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-decoder
    restart: unless-stopped
    ports:
      - '8889'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8889/health'
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PORT=8889
      - SERVICE_FQDN_ZAPIMEDIAAPI_8889
